apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-routine-api-deployment
  namespace: $APP_NAME
spec:  
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      name: $APP_NAME
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: transaction-routine-api-container
        image: olivaldofilho/transaction-routine-api:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: transaction-routine-api-configmap
        - secretRef:
            name: transaction-routine-api-secret
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3        
      imagePullSecrets:
      - name: regcred