apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: transaction-routine-api
spec:
  limits:
    - default:
        cpu: 100m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      type: Container

