apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-routine-api-hpa
  namespace: transaction-routine-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-routine-api-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50