apiVersion: v1
kind: Pod
metadata:
  name: transactiondb-pod
  namespace: transaction-routine-api
  labels:
    app: transactiondb
spec:
  containers:
  - name: transactiondb-container
    image: postgres
    ports:
    - containerPort: 5432
    envFrom:
    - configMapRef:
        name: transactiondb-configmap